id: I94A937EA
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-15T20:12:05.206029'
last_modified: '2022-06-15T20:12:05.206057'
parser: null
source_metadata:
  title: Śavari
  language: en
  description: 'Texts by and about the mahāsiddha Śavari/Śabari (ri khrod zhabs),
    the Hunter:'
  volume:
    fB124:
      title: A Guru Yoga of Śavari
      base_file: fB124.txt
      order: 1
      parent: Guru Yoga
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
